# Generated by Django 5.1.2 on 2024-10-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_assignment_created_at_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
